In [1]:
from DataGroundTruth import DataGroundTruth
import geopandas as gpd
import numpy as np

In [2]:
fb = 177
dgt = DataGroundTruth('/media/philipp/DATA/2018_tamsweg/')
#dgt = DataGroundTruth('/media/philipp/DATA/2018_tamsweg_predict/')

In [3]:
# ground truth
path_dir = "/media/philipp/DATA/2018_tamsweg/"
path_shp = "/home/philipp/Data/edin_diss/GIS_ground_truth/df_2020_2/gis_df_wwie_2020_177_adj_0801.shp".format(fb)
name_vector = "gis_df_wwie_2020_177_adj_0801"
name_layer = "typ_ac1"

In [3]:
# ground truth mask
path_dir = "/media/philipp/DATA/2018_tamsweg/"
path_shp = "/home/philipp/Data/edin_diss/GIS_ground_truth/df_2020_2/gis_df_wwie_2020_177_adj_0801.shp".format(fb)
name_vector = "gis_df_wwie_2020_177_adj_0801"
name_layer = "typ_ac1_m"

In [5]:
# age
path_dir = "/media/philipp/DATA/2018_tamsweg/"
path_shp = "/home/philipp/Data/edin_diss/GIS_ground_truth/df_2020_2/gis_df_wwie_2020_177_adj.shp".format(fb)
name_vector = "gis_df_wwie_2020_177_adj"
name_layer = "age"

In [5]:
path_dir = "/media/philipp/DATA/2018_tamsweg_predict/"
path_shp = "/home/philipp/Data/edin_diss/GIS_ground_truth/df_2020_age/gis_df_wwie_2020_typ_177.shp".format(fb)
name_vector = "gis_df_wwie_2020_typ_177"
name_layer = "typ"

In [10]:
path_dir = "/media/philipp/DATA/2018_tamsweg_predict/"
path_shp = "/home/philipp/Data/edin_diss/GIS_ground_truth/df_mask/gis_df_wwie_2020_177_mask.shp".format(fb)
name_vector = "gis_df_wwie_2020_177_mask"
name_layer = "mask"

In [4]:
dgt.create_raster(path_dir, path_shp, name_vector, name_layer, "ground_truth_ac1_mask")

0%
10%
20%
30%
40%
50%
60%
70%
80%
90%
100%


In [3]:
path_file = "/home/philipp/Data/edin_diss/GIS_ground_truth/df_2020_2/gis_df_wwie_2020_177_adj.shp".format(fb)
wo_geo = gpd.read_file(path_file)

In [5]:
wo_geo

fb   fr  abt uabt  teilfl  admin       length          area  \
0      177  6.0  144    A       1    609   721.648071  17171.469012   
1      177  6.0  144    A       1    609   806.381470  15887.334816   
2      177  6.0  144    A       2    609  1180.373535  24672.718591   
3      177  6.0  144    A       3    609   794.072571  12975.168827   
4      177  6.0  144    B       0    609   786.788513  31480.237381   
...    ...  ...  ...  ...     ...    ...          ...           ...   
16334  177  6.0  115    L       2    609   716.279724  14860.519932   
16335  177  6.0   94    E       3    609   778.799011   8880.082342   
16336  177  6.0   94    E       2    609   818.324341  13888.328888   
16337  177  6.0   94    E       3    609   309.558838   5144.376851   
16338  177  6.0   94    A       3    609   458.650513   6474.987940   

         fly_date  year_fly  ... cut_v_lh  cut_v_nh  cut_v_nan  cut_v_tot typ  \
0      26.06.2019      2019  ...      0.0     159.0        0.0      159.0   2   
1      26.06.2019      2019  ...      0.0     159.0        0.0      159.0   2   
2      26.06.2019      2019  ...      0.0       0.0        0.0        0.0   1   
3      26.06.2019      2019  ...      0.0       0.0        0.0        0.0   2   
4      26.06.2019      2019  ...      0.0       0.0        0.0        0.0   2   
...           ...       ...  ...      ...       ...        ...        ...  ..   
16334  03.07.2018      2018  ...      0.0       0.0        0.0        0.0   2   
16335  03.07.2018      2018  ...      0.0       4.0        0.0        4.0   2   
16336  03.07.2018      2018  ...      0.0       0.0        0.0        0.0   1   
16337  03.07.2018      2018  ...      0.0       4.0        0.0        4.0   1   
16338  03.07.2018      2018  ...      0.0       0.0        0.0        0.0   1   

       typ_std typ_add  typ_ac12  typ_ac1  \
0            3       3         3        3   
1            3       3         3        3   
2            1       1         2        0   
3            3       3         3        3   
4            3       3         3        3   
...        ...     ...       ...      ...   
16334        3       3         3        3   
16335        3       3         3        3   
16336        1       1         1        1   
16337        1       1         1        1   
16338        1       1         2        0   

                                                geometry  
0      POLYGON ((448743.510 361073.725, 448760.100 36...  
1      POLYGON ((448527.110 361004.735, 448537.420 36...  
2      POLYGON ((448568.770 361060.358, 448571.558 36...  
3      POLYGON ((448806.209 360932.529, 448771.984 36...  
4      POLYGON ((448831.663 360987.284, 448834.340 36...  
...                                                  ...  
16334  POLYGON ((436334.301 367768.944, 436313.016 36...  
16335  POLYGON ((435918.087 367143.872, 435937.784 36...  
16336  POLYGON ((436122.822 366776.153, 436102.120 36...  
16337  POLYGON ((436010.856 366781.393, 436001.911 36...  
16338  POLYGON ((435672.175 366615.818, 435655.197 36...  

[16339 rows x 69 columns]

In [ ]:
##########################
# adjusted ground truth
##########################

In [7]:
# create shape with just ground truth type

path_file = "/home/philipp/Data/edin_diss/GIS_ground_truth/df_2020_2/gis_df_wwie_2020_{}.shp".format(fb)
wo_geo = gpd.read_file(path_file)

# create geo-dataframe
wo_typ = wo_geo[['typ', 'geometry']]

# save to file
wo_typ.to_file("/home/philipp/Data/edin_diss/GIS_ground_truth/df_2020_2/gis_df_wwie_2020_typ_{}_adjusted.shp".format(fb))

In [ ]:
# create shape with just age type

path_file = "/home/philipp/Data/edin_diss/GIS_ground_truth/df_2020_2/gis_df_wwie_2020_{}.shp".format(fb)
wo_geo = gpd.read_file(path_file)

# create geo-dataframe
wo_typ = wo_geo[['age', 'geometry']]

# save to file
wo_typ.to_file("/home/philipp/Data/edin_diss/GIS_ground_truth/df_2020_age/gis_df_wwie_2020_typ_{}_adjusted.shp".format(fb))

In [ ]:
################
# rename files
################

In [3]:
paths = dgt.get_file_paths(path_dir+'ground_truth_std')

NameError: name 'path_dir' is not defined

In [20]:
paths

['tile_ground_truth_167401.tif',
 'tile_ground_truth_188409.tif',
 'tile_ground_truth_150388.tif',
 'tile_ground_truth_195329.tif',
 'tile_ground_truth_184749.tif',
 'tile_ground_truth_167989.tif',
 'tile_ground_truth_193219.tif',
 'tile_ground_truth_144770.tif',
 'tile_ground_truth_147193.tif',
 'tile_ground_truth_154542.tif',
 'tile_ground_truth_204644.tif',
 'tile_ground_truth_123949.tif',
 'tile_ground_truth_201001.tif',
 'tile_ground_truth_151582.tif',
 'tile_ground_truth_186649.tif',
 'tile_ground_truth_152003.tif',
 'tile_ground_truth_183141.tif',
 'tile_ground_truth_132504.tif',
 'tile_ground_truth_156495.tif',
 'tile_ground_truth_196044.tif',
 'tile_ground_truth_155520.tif',
 'tile_ground_truth_191014.tif',
 'tile_ground_truth_153308.tif',
 'tile_ground_truth_145258.tif',
 'tile_ground_truth_143482.tif',
 'tile_ground_truth_147823.tif',
 'tile_ground_truth_199132.tif',
 'tile_ground_truth_199680.tif',
 'tile_ground_truth_195558.tif',
 'tile_ground_truth_154785.tif',
 'tile_gro

In [4]:
import os

In [5]:
path_dir = "/media/philipp/DATA/2018_tamsweg/ground_truth_std/"

In [6]:
for path in paths:
    os.rename(path_dir+path, "{}tile_ground_truth_std{}".format(path_dir, path[path.rfind('_'):]))

NameError: name 'paths' is not defined

In [7]:
################
# add ground truth types
################

In [8]:
path_shp = "/home/philipp/Data/edin_diss/GIS_ground_truth/df_2020_2/gis_df_wwie_2020_177.shp"
wo_geo = gpd.read_file(path_shp)

In [9]:
wo_geo.head()

fb   fr  abt uabt  teilfl  admin       length          area    fly_date  \
0  177  6.0  144    A       1    609   721.648071  17171.469012  26.06.2019   
1  177  6.0  144    A       1    609   806.381470  15887.334816  26.06.2019   
2  177  6.0  144    A       2    609  1180.373535  24672.718591  26.06.2019   
3  177  6.0  144    A       3    609   794.072571  12975.168827  26.06.2019   
4  177  6.0  144    B       0    609   786.788513  31480.237381  26.06.2019   

   year_fly  ... fly_y  fly_m  fly_d  cut_ma cut_v_lh  cut_v_nh cut_v_nan  \
0      2019  ...  2019      6     26  ['SW']      0.0     159.0       0.0   
1      2019  ...  2019      6     26  ['SW']      0.0     159.0       0.0   
2      2019  ...  2019      6     26    None      0.0       0.0       0.0   
3      2019  ...  2019      6     26    None      0.0       0.0       0.0   
4      2019  ...  2019      6     26    None      0.0       0.0       0.0   

   cut_v_tot  typ                                           geometry  
0      159.0    2  POLYGON ((448743.510 361073.725, 448760.100 36...  
1      159.0    2  POLYGON ((448527.110 361004.735, 448537.420 36...  
2        0.0    1  POLYGON ((448568.770 361060.358, 448571.558 36...  
3        0.0    2  POLYGON ((448806.209 360932.529, 448771.984 36...  
4        0.0    2  POLYGON ((448831.663 360987.284, 448834.340 36...  

[5 rows x 65 columns]

In [10]:
# std
# conditions 0 = void, 1 = thinning (ac1+2), 3 = no thinning, 4 = else
conditions = [
    (wo_geo['typ'] == 0),
    (wo_geo['typ'] == 1),
    ((wo_geo['typ'] == 2) | (wo_geo['typ'] == 4)),
    (wo_geo['typ'] == 3)]

choices = [0, 1, 2, 3]

wo_geo['typ_std'] = np.select(conditions, choices, default=0)

In [11]:
# add
# conditions 0 = void, 1 = thinning, 5 = just thinned, 3 = no thinning, 4 = else
conditions = [
    (wo_geo['typ'] == 0),
    (wo_geo['typ'] == 1),
    (wo_geo['typ'] == 4),
    (wo_geo['typ'] == 2),
    (wo_geo['typ'] == 3)]

choices = [0, 1, 2, 3, 4]

wo_geo['typ_add'] = np.select(conditions, choices, default=0)

In [12]:
# acutness 1 & 2
# conditions 0 = void, 1 = thinning (ac1), 2 = thinning (ac2), 3 = no thinning, 4 = else
conditions = [
    (wo_geo['typ'] == 0),
    ((wo_geo['typ'] == 1) & (wo_geo['dr'] == 1)),
    ((wo_geo['typ'] == 1) & ((wo_geo['dr'] == 0) | (wo_geo['dr'] > 1))),
    ((wo_geo['typ'] == 2) | (wo_geo['typ'] == 4)),
    (wo_geo['typ'] == 3)]

choices = [0, 1, 2, 3, 4]

wo_geo['typ_ac12'] = np.select(conditions, choices, default=0)

In [13]:
# acutness 1
# conditions 0 = void, 1 = thinning (ac1), 3 = no thinning, 4 = else
conditions = [
    (wo_geo['typ'] == 0), \
    ((wo_geo['typ'] == 1) & (wo_geo['dr'] == 1)), \
    (((wo_geo['typ'] == 1) & (wo_geo['dr'] != 1)) | \
     (wo_geo['typ'] == 2) | \
     (wo_geo['typ'] == 4)), \
    (wo_geo['typ'] == 3)]

choices = [0, 1, 2, 3]

wo_geo['typ_ac1'] = np.select(conditions, choices, default=0)

In [15]:
############
# set mask
# economy = I; ww_sw = W; age < uz -20
wo_geo['typ_mask'] = 0
wo_geo.loc[(wo_geo['ww_sw']=='W') & \
           (wo_geo['economy']=='I') & \
           (wo_geo['age']<=wo_geo['uz']-20), 'typ_mask'] = \
wo_geo.loc[(wo_geo['ww_sw']=='W') & \
           (wo_geo['economy']=='I') & \
           (wo_geo['age']<=wo_geo['uz']-20), 'typ']

# print shape
wo_geo.loc[(wo_geo['ww_sw']=='W') & \
           (wo_geo['economy']=='I') & \
           (wo_geo['age']<=wo_geo['uz']-20),:].shape

(8771, 70)

In [16]:
## std_mask
# conditions 0 = void, 1 = thinning (ac1+2), 3 = no thinning, 4 = else
conditions = [
    (wo_geo['typ_mask'] == 0),
    (wo_geo['typ_mask'] == 1),
    ((wo_geo['typ_mask'] == 2) | (wo_geo['typ_mask'] == 4)),
    (wo_geo['typ_mask'] == 3)]

choices = [0, 1, 2, 3]

wo_geo['typ_std_m'] = np.select(conditions, choices, default=0)

In [17]:
## acutness 1 & 2 mask
# conditions 0 = void, 1 = thinning (ac1), 2 = thinning (ac2), 3 = no thinning, 4 = else
conditions = [
    (wo_geo['typ_mask'] == 0),
    ((wo_geo['typ_mask'] == 1) & (wo_geo['dr'] == 1)),
    ((wo_geo['typ_mask'] == 1) & ((wo_geo['dr'] == 0) | (wo_geo['dr'] > 1))),
    ((wo_geo['typ_mask'] == 2) | (wo_geo['typ_mask'] == 4)),
    (wo_geo['typ_mask'] == 3)]

choices = [0, 1, 2, 3, 4]

wo_geo['typ_ac12_m'] = np.select(conditions, choices, default=0)

In [18]:
# acutness 1
# conditions 0 = void, 1 = thinning (ac1), 3 = no thinning, 4 = else
conditions = [
    (wo_geo['typ_mask'] == 0),
    ((wo_geo['typ_mask'] == 1) & (wo_geo['dr'] == 1)),
    (((wo_geo['typ_mask'] == 1) & (wo_geo['dr'] != 1)) | \
     (wo_geo['typ_mask'] == 2) | \
     (wo_geo['typ_mask'] == 4)),
    (wo_geo['typ_mask'] == 3)]

choices = [0, 1, 2, 3]

wo_geo['typ_ac1_m'] = np.select(conditions, choices, default=0)

In [20]:
wo_geo.to_file("/home/philipp/Data/edin_diss/GIS_ground_truth/df_2020_2/gis_df_wwie_2020_177_adj_0801.shp")

In [1]:
import numpy as np

In [9]:
x = np.arange(16*5).reshape((5, 4, 4))

In [10]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]],

       [[64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]]])

In [11]:
yx[:,:2,:2]

array([[[ 0,  1],
        [ 4,  5]],

       [[16, 17],
        [20, 21]],

       [[32, 33],
        [36, 37]],

       [[48, 49],
        [52, 53]],

       [[64, 65],
        [68, 69]]])

In [13]:
y = np.concatenate([x[:, :2, :2], \
                    x[:, 2:, :2], \
                    x[:, :2, 2:], \
                    x[:, 2:, 2:]], axis=0)

In [14]:
y

array([[[ 0,  1],
        [ 4,  5]],

       [[16, 17],
        [20, 21]],

       [[32, 33],
        [36, 37]],

       [[48, 49],
        [52, 53]],

       [[64, 65],
        [68, 69]],

       [[ 8,  9],
        [12, 13]],

       [[24, 25],
        [28, 29]],

       [[40, 41],
        [44, 45]],

       [[56, 57],
        [60, 61]],

       [[72, 73],
        [76, 77]],

       [[ 2,  3],
        [ 6,  7]],

       [[18, 19],
        [22, 23]],

       [[34, 35],
        [38, 39]],

       [[50, 51],
        [54, 55]],

       [[66, 67],
        [70, 71]],

       [[10, 11],
        [14, 15]],

       [[26, 27],
        [30, 31]],

       [[42, 43],
        [46, 47]],

       [[58, 59],
        [62, 63]],

       [[74, 75],
        [78, 79]]])

In [20]:
y[[0,5,10,15]]

array([[[ 0,  1],
        [ 4,  5]],

       [[ 8,  9],
        [12, 13]],

       [[ 2,  3],
        [ 6,  7]],

       [[10, 11],
        [14, 15]]])