In [1]:
import os
import numpy as np
import h5py
from DatasetCreation import DatasetCreation

In [2]:
path_hdf5 = '/media/philipp/DATA/dataset/dataset_256_df_177.h5'
#dataset_256_df_177.h5'
hdf5_ds = h5py.File(path_hdf5, 'r')

In [3]:
hdf5_ds['dsm']

<HDF5 dataset "dsm": shape (42716, 256, 256, 1), type "<f2">

In [4]:
hdf5_ds.keys()

<KeysViewHDF5 ['age', 'dsm', 'dtm', 'ground_truth_ac1', 'ground_truth_ac12', 'ground_truth_std', 'ortho', 'slope']>

In [5]:
path_load = '/home/philipp/Data/edin_index/train_indices.npy'
train = np.sort(np.load(path_load))

path_load = '/home/philipp/Data/edin_index/val_indices.npy'
val = np.sort(np.load(path_load))

path_load = '/home/philipp/Data/edin_index/test_indices.npy'
test = np.sort(np.load(path_load))

In [6]:
train

array([    0,     1,     2, ..., 42713, 42714, 42715])

In [7]:
val

array([    7,    14,    17, ..., 42697, 42707, 42710])

In [8]:
idx = np.sort(np.concatenate((train, val)))

In [9]:
idx

array([    0,     1,     2, ..., 42713, 42714, 42715])

In [10]:
print(train.shape)
print(val.shape)
print(test.shape)

(29908,)
(4268,)
(8540,)


In [11]:
29908+4268

34176

In [12]:
train[25000:25100]

array([35742, 35743, 35744, 35745, 35746, 35747, 35748, 35749, 35750,
       35752, 35753, 35754, 35755, 35756, 35757, 35758, 35759, 35760,
       35761, 35762, 35764, 35766, 35767, 35768, 35769, 35772, 35773,
       35775, 35777, 35778, 35779, 35780, 35784, 35786, 35787, 35789,
       35790, 35792, 35794, 35795, 35796, 35798, 35799, 35800, 35801,
       35804, 35806, 35807, 35809, 35810, 35811, 35812, 35813, 35814,
       35815, 35816, 35818, 35822, 35823, 35825, 35826, 35829, 35830,
       35831, 35833, 35834, 35836, 35838, 35839, 35841, 35843, 35844,
       35846, 35848, 35849, 35850, 35852, 35853, 35854, 35855, 35856,
       35857, 35859, 35860, 35862, 35864, 35865, 35866, 35867, 35868,
       35870, 35872, 35873, 35874, 35875, 35876, 35877, 35879, 35880,
       35882])

In [13]:
hdf5_ds['dsm'][40000:40100].shape

(100, 256, 256, 1)

In [14]:
hdf5_ds['dsm'][train[25000:26000]].shape

(1000, 256, 256, 1)

In [15]:
hdf5_ds.close()

In [43]:
#####################################################################################

In [16]:
# create dataset

In [16]:
def create_hdf5(path_file, tile_size, dataset_size):
    path_hdf5 = path_file
    # cerate file
    hdf5_ds = h5py.File(path_file, 'a')
    # create dataset
    for data_type in data_types:
        x = hdf5_ds.create_dataset(data_type, \
        (dataset_size, tile_size, tile_size, data_dic[data_type]['dim']), \
        dtype=data_dic[data_type]['dtype'])
    hdf5_ds.close()

In [18]:
type_mask='ground_truth_std'
data_dic = {'ortho':{'dtype':np.uint8, 'dim':4}, \
            'dsm':{'dtype':np.float16, 'dim':1}, \
            'dtm':{'dtype':np.float16, 'dim':1}, \
            'slope':{'dtype':np.float16, 'dim':1}, \
            'age':{'dtype':np.uint8, 'dim':1}, \
            'ground_truth_std':{'dtype':np.uint8, 'dim':1}, \
            'ground_truth_ac12':{'dtype':np.uint8, 'dim':1}, \
            'ground_truth_ac1':{'dtype':np.uint8, 'dim':1}}

data_types = list(data_dic.keys())

In [17]:
### mask ###
'''
type_mask='ground_truth_std_mask'
data_dic = {'ortho':{'dtype':np.uint8, 'dim':4}, \
            'dsm':{'dtype':np.float16, 'dim':1}, \
            'dtm':{'dtype':np.float16, 'dim':1}, \
            'slope':{'dtype':np.float16, 'dim':1}, \
            'age':{'dtype':np.uint8, 'dim':1}, \
            'ground_truth_std_mask':{'dtype':np.uint8, 'dim':1}, \
            'ground_truth_ac12_mask':{'dtype':np.uint8, 'dim':1}, \
            'ground_truth_ac1_mask':{'dtype':np.uint8, 'dim':1}}

data_types = list(data_dic.keys())
'''

In [19]:
# set output path
path_hdf5 = '/media/philipp/DATA/dataset/dataset_ext_256_df_177.h5'

if not os.path.isfile(path_hdf5):
    print('file not found -> creating file')
    # create new hdf5 file
    create_hdf5(path_hdf5, tile_size=256, dataset_size=10679*4+34176) # tams: 39280, bisch: 35272
else:
    print('file existing')

file not found -> creating file


In [18]:
### mask ###
# set output path
'''
path_hdf5 = '/media/philipp/DATA/dataset/dataset_mask_ext_256_df_177.h5'

if not os.path.isfile(path_hdf5):
    print('file not found -> creating file')
    # create new hdf5 file
    create_hdf5(path_hdf5, tile_size=256, dataset_size=10679*4+34176) # tams: 39280, bisch: 35272
else:
    print('file existing')
'''

file not found -> creating file


In [20]:
#######################################################################################
# feed data

In [19]:
# set output path
path_main = '/media/philipp/DATA/dataset/dataset_256_df_177.h5'
#path_main = '/media/philipp/DATA/dataset/dataset_mask_256_df_177.h5'
# load data
main_ds = h5py.File(path_main, 'r')

In [20]:
# set output path
path_hdf5 = '/media/philipp/DATA/dataset/dataset_ext_256_df_177.h5'
#path_hdf5 = '/media/philipp/DATA/dataset/dataset_mask_ext_256_df_177.h5'
# load data
hdf5_ds = h5py.File(path_hdf5, 'a')

In [21]:
main_ds['ortho']

<HDF5 dataset "ortho": shape (42716, 256, 256, 4), type "|u1">

In [22]:
hdf5_ds['ortho']

<HDF5 dataset "ortho": shape (76892, 256, 256, 4), type "|u1">

In [23]:
# copy original
for data_type in data_types:
    # set dataset
    source = main_ds[data_type]
    # set dataset
    target = hdf5_ds[data_type]
    # assign data
    target[:20000,:,:,:] = source[:20000,:,:,:]

In [24]:
# copy original
for data_type in data_types:
    # set dataset
    source = main_ds[data_type]
    # set dataset
    target = hdf5_ds[data_type]
    # assign data
    target[20000:42716,:,:,:] = source[20000:42716,:,:,:]

In [25]:
# copy fliped
for data_type in data_types:
    # set dataset
    source = main_ds[data_type]
    # set dataset
    target = hdf5_ds[data_type]
    # assign data
    target[42716:42716+10000,:,:,:] = np.flip(source[idx[:10000],:,:,:], axis=2)

In [26]:
# copy fliped
for data_type in data_types:
    # set dataset
    source = main_ds[data_type]
    # set dataset
    target = hdf5_ds[data_type]
    # assign data
    target[42716+10000:42716+20000,:,:,:] = np.flip(source[idx[10000:20000],:,:,:], axis=2)

In [27]:
# copy fliped
for data_type in data_types:
    # set dataset
    source = main_ds[data_type]
    # set dataset
    target = hdf5_ds[data_type]
    # assign data
    target[42716+20000:42716+30000,:,:,:] = np.flip(source[idx[20000:30000],:,:,:], axis=2)

In [28]:
# copy fliped
for data_type in data_types:
    # set dataset
    source = main_ds[data_type]
    # set dataset
    target = hdf5_ds[data_type]
    # assign data
    target[42716+30000:42716+34176,:,:,:] = np.flip(source[idx[30000:34176],:,:,:], axis=2)

In [29]:
hdf5_ds.close()
main_ds.close()

In [ ]:
#######################################################################################
########################
# add stats to dataset
########################

In [32]:
#####################
# tamsweg (177)
#--------------------
# ortho
ortho_m = np.array([56.12055784563426, 62.130400134006976, 53.03228547781888, 119.50916281232037], dtype='float32')
ortho_s = np.array([30.37628560708646, 30.152693706272483, 23.13718651792004, 49.301477498205074], dtype='float32')
#--------------------
# dsm
dsm_m = np.array([13.45], dtype='float32')
dsm_s = np.array([10.386633252098674], dtype='float32')
#--------------------
# dtm
dtm_m = np.array([1446.0], dtype='float32')
dtm_s = np.array([271.05322202384195], dtype='float32')
#--------------------
# slope
slope_m = np.array([22.39], dtype='float32')
slope_s = np.array([11.69830556896441], dtype='float32')
#--------------------
# age
age_m = np.array([78.5], dtype='float32')
age_s = np.array([62.3], dtype='float32')
#####################

In [30]:
#####################
# tamsweg (177) mask
#--------------------
# ortho
ortho_m = np.array([33.82914264113484, 37.55754176873104, 31.903114954332853, 74.5179778501909], dtype='float32')
ortho_s = np.array([35.77673396410279, 38.05332744218563, 31.1493457987135, 71.2077061375181], dtype='float32')
#--------------------
# dsm
dsm_m = np.array([7.913559175718699], dtype='float32')
dsm_s = np.array([9.694446633486207], dtype='float32')
#--------------------
# dtm
dtm_m = np.array([863.1380279052345], dtype='float32')
dtm_s = np.array([731.0248602823007], dtype='float32')
#--------------------
# slope
slope_m = np.array([13.615414891375597], dtype='float32')
slope_s = np.array([13.993867741806872], dtype='float32')
#####################

In [31]:
path_hdf5 = '/media/philipp/DATA/dataset/dataset_ext_256_df_177.h5'
#path_hdf5 = '/media/philipp/DATA/dataset/dataset_mask_ext_256_df_177.h5'
with h5py.File(path_hdf5, 'a') as hdf5_ds:
    # ortho
    hdf5_ds['ortho'].attrs['mean'] = ortho_m
    hdf5_ds['ortho'].attrs['sd'] = ortho_s
    # dsm
    hdf5_ds['dsm'].attrs['mean'] = dsm_m
    hdf5_ds['dsm'].attrs['sd'] = dsm_s
    # dtm
    hdf5_ds['dtm'].attrs['mean'] = dtm_m
    hdf5_ds['dtm'].attrs['sd'] = dtm_s
    # slope
    hdf5_ds['slope'].attrs['mean'] = slope_m
    hdf5_ds['slope'].attrs['sd'] = slope_s
    # age
    #hdf5_ds['age'].attrs['mean'] = age_m
    #hdf5_ds['age'].attrs['sd'] = age_s

In [32]:
path_hdf5 = '/media/philipp/DATA/dataset/dataset_mask_ext_256_df_177.h5'
hdf5_ds = h5py.File(path_hdf5, 'r')

In [33]:
hdf5_ds['ortho'].attrs.keys()

<KeysViewHDF5 ['mean', 'sd']>

In [34]:
hdf5_ds.close()

In [3]:
# set output path
path_hdf5 = '/media/philipp/DATA/dataset/dataset_ext_256_df_177.h5'
# load data
hdf5_ds = h5py.File(path_hdf5, 'r')

In [4]:
hdf5_ds['ortho'][70338]

array([[[ 29,  36,  41,  47],
        [ 27,  33,  36,  44],
        [ 29,  35,  40,  48],
        ...,
        [ 87,  94,  83, 164],
        [ 80,  87,  74, 155],
        [ 76,  83,  69, 151]],

       [[ 30,  37,  44,  49],
        [ 25,  30,  34,  42],
        [ 26,  33,  37,  45],
        ...,
        [ 68,  73,  59, 141],
        [ 56,  57,  39, 123],
        [ 59,  60,  43, 126]],

       [[ 27,  33,  40,  45],
        [ 27,  33,  40,  46],
        [ 29,  36,  45,  50],
        ...,
        [ 54,  56,  37, 120],
        [ 61,  64,  47, 131],
        [ 80,  86,  75, 160]],

       ...,

       [[ 30,  36,  38,  62],
        [ 28,  35,  35,  62],
        [ 29,  36,  37,  66],
        ...,
        [ 66,  76,  71, 137],
        [ 67,  75,  70, 138],
        [ 57,  63,  56, 122]],

       [[ 28,  33,  36,  59],
        [ 29,  36,  40,  66],
        [ 29,  37,  39,  68],
        ...,
        [ 61,  68,  60, 128],
        [ 61,  68,  61, 127],
        [ 54,  59,  51, 115]],

       [[ 26

In [5]:
hdf5_ds.keys()

<KeysViewHDF5 ['age', 'dsm', 'dtm', 'ground_truth_ac1', 'ground_truth_ac12', 'ground_truth_std', 'ortho', 'slope']>

In [6]:
hdf5_ds['ground_truth_ac12']

<HDF5 dataset "ground_truth_ac12": shape (76892, 256, 256, 1), type "|u1">

In [23]:
hdf5_ds.close()